version: '3.9'

services:

  minio:
    image: docker.arvancloud.ir/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: VEWxBSnQWS5fQJwsF5szwFrtwnwfmpFR
    command: server --console-address ":9001" /data

  pgvector:
    image: docker.arvancloud.ir/ankane/pgvector
    environment:
      - POSTGRES_DB=pgvector
      - POSTGRES_USER=pgvector
      - POSTGRES_PASSWORD=pgvectorq@
    volumes:
      - ./pgvector/scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data:rw
      - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'

volumes:
  minio_storage: {}
  db-data: { }